// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Load_Profile
void ui_Load_Profile_screen_init(void);
void ui_event_Load_Profile(lv_event_t * e);
lv_obj_t * ui_Load_Profile;
lv_obj_t * ui_Panel14;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Label4;
void ui_event_BuCloseLoadProfile(lv_event_t * e);
lv_obj_t * ui_BuCloseLoadProfile;
lv_obj_t * ui_Panel39;
lv_obj_t * ui_PanelProfile1;
lv_obj_t * ui_PanelPreheat2;
lv_obj_t * ui_LabelPreheat20;
lv_obj_t * ui_laProfile1;
lv_obj_t * ui_Panel41;
void ui_event_BuSettingsProfile1(lv_event_t * e);
lv_obj_t * ui_BuSettingsProfile1;
void ui_event_BuSelectProfile1(lv_event_t * e);
lv_obj_t * ui_BuSelectProfile1;
void ui_event_Label34(lv_event_t * e);
lv_obj_t * ui_Label34;
lv_obj_t * ui_PanelProfile2;
lv_obj_t * ui_PanelPreheat1;
lv_obj_t * ui_LabelPreheat2;
lv_obj_t * ui_laProfile2;
lv_obj_t * ui_Panel26;
void ui_event_BuSettingsProfile2(lv_event_t * e);
lv_obj_t * ui_BuSettingsProfile2;
void ui_event_BuSelectProfile2(lv_event_t * e);
lv_obj_t * ui_BuSelectProfile2;
lv_obj_t * ui_Label10;
lv_obj_t * ui_PanelProfile3;
lv_obj_t * ui_PanelPreheat3;
lv_obj_t * ui_LabelPreheat21;
lv_obj_t * ui_laProfile3;
lv_obj_t * ui_Panel43;
void ui_event_BuSettingsProfile3(lv_event_t * e);
lv_obj_t * ui_BuSettingsProfile3;
void ui_event_BuSelectProfile3(lv_event_t * e);
lv_obj_t * ui_BuSelectProfile3;
lv_obj_t * ui_Label13;
lv_obj_t * ui_PanelProfile4;
lv_obj_t * ui_PanelPreheat4;
lv_obj_t * ui_LabelPreheat22;
lv_obj_t * ui_laProfile4;
lv_obj_t * ui_Panel45;
void ui_event_BuSettingsProfile4(lv_event_t * e);
lv_obj_t * ui_BuSettingsProfile4;
void ui_event_BuSelectProfile4(lv_event_t * e);
lv_obj_t * ui_BuSelectProfile4;
lv_obj_t * ui_Label8;
lv_obj_t * ui_PanelProfile5;
lv_obj_t * ui_PanelPreheat10;
lv_obj_t * ui_LabelPreheat23;
lv_obj_t * ui_laProfile5;
lv_obj_t * ui_Panel47;
void ui_event_BuSettingsProfile5(lv_event_t * e);
lv_obj_t * ui_BuSettingsProfile5;
void ui_event_BuSelectProfile5(lv_event_t * e);
lv_obj_t * ui_BuSelectProfile5;
lv_obj_t * ui_Label11;
// CUSTOM VARIABLES
lv_obj_t * uic_Panel1;
lv_obj_t * uic_Panel1;
lv_obj_t * uic_Panel1;
lv_obj_t * uic_Panel1;
lv_obj_t * uic_Panel1;


// SCREEN: ui_Reflow_Oven
void ui_Reflow_Oven_screen_init(void);
lv_obj_t * ui_Reflow_Oven;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Image4;
lv_obj_t * ui_LaMenuTitle;
lv_obj_t * ui_Chart1;
lv_obj_t * ui_LaActualTemperature;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_PanelPreheat5;
lv_obj_t * ui_LabelPreheat5;
lv_obj_t * ui_laPreheatTempRise;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_PanelPreheat6;
lv_obj_t * ui_LabelPreheat6;
lv_obj_t * ui_laSoakTemp;
lv_obj_t * ui_laSoakDur;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_PanelPreheat7;
lv_obj_t * ui_LabelPreheat7;
lv_obj_t * ui_laRampPeakTempRise;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_PanelPreheat8;
lv_obj_t * ui_LabelPreheat8;
lv_obj_t * ui_laReflowTemp;
lv_obj_t * ui_laReflowDur;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_PanelPreheat9;
lv_obj_t * ui_LabelPreheat9;
lv_obj_t * ui_laCooldownTemp;
lv_obj_t * ui_laCooldownDur;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Panel13;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label29;
void ui_event_BuNewProfile(lv_event_t * e);
lv_obj_t * ui_BuNewProfile;
lv_obj_t * ui_Label7;
void ui_event_BuLoadProfile(lv_event_t * e);
lv_obj_t * ui_BuLoadProfile;
lv_obj_t * ui_Label5;
// CUSTOM VARIABLES
lv_obj_t * uic_Panel1;
lv_obj_t * uic_Panel1;
lv_obj_t * uic_Panel1;
lv_obj_t * uic_Panel1;
lv_obj_t * uic_Panel1;


// SCREEN: ui_New_Profile
void ui_New_Profile_screen_init(void);
lv_obj_t * ui_New_Profile;
lv_obj_t * ui_Panel38;
lv_obj_t * ui_Image10;
lv_obj_t * ui_Label3;
void ui_event_BuCloseNewProfile(lv_event_t * e);
lv_obj_t * ui_BuCloseNewProfile;
lv_obj_t * ui_Panel15;
lv_obj_t * ui_Panel37;
lv_obj_t * ui_Panel16;
lv_obj_t * ui_Label2;
void ui_event_taProfileName(lv_event_t * e);
lv_obj_t * ui_taProfileName;
lv_obj_t * ui_Panel32;
lv_obj_t * ui_Panel17;
lv_obj_t * ui_LabelPreheat1;
lv_obj_t * ui_Panel18;
lv_obj_t * ui_LabelPreheat3;
void ui_event_taPreheatTempRise(lv_event_t * e);
lv_obj_t * ui_taPreheatTempRise;
lv_obj_t * ui_Panel33;
lv_obj_t * ui_Panel25;
lv_obj_t * ui_LabelPreheat14;
lv_obj_t * ui_Panel21;
lv_obj_t * ui_LabelPreheat4;
void ui_event_taSoakTemp(lv_event_t * e);
lv_obj_t * ui_taSoakTemp;
lv_obj_t * ui_Panel22;
lv_obj_t * ui_LabelPreheat10;
void ui_event_taSoakDur(lv_event_t * e);
lv_obj_t * ui_taSoakDur;
lv_obj_t * ui_Panel34;
lv_obj_t * ui_Panel27;
lv_obj_t * ui_LabelPreheat15;
lv_obj_t * ui_Panel20;
lv_obj_t * ui_LabelPreheat11;
void ui_event_taRampUpTempRise(lv_event_t * e);
lv_obj_t * ui_taRampUpTempRise;
lv_obj_t * ui_Panel35;
lv_obj_t * ui_Panel28;
lv_obj_t * ui_LabelPreheat16;
lv_obj_t * ui_Panel23;
lv_obj_t * ui_LabelPreheat12;
void ui_event_taReflowTemp(lv_event_t * e);
lv_obj_t * ui_taReflowTemp;
lv_obj_t * ui_Panel24;
lv_obj_t * ui_LabelPreheat13;
void ui_event_taReflowDur(lv_event_t * e);
lv_obj_t * ui_taReflowDur;
lv_obj_t * ui_Panel36;
lv_obj_t * ui_Panel29;
lv_obj_t * ui_LabelPreheat17;
lv_obj_t * ui_Panel30;
lv_obj_t * ui_LabelPreheat18;
void ui_event_taCooldownTemp(lv_event_t * e);
lv_obj_t * ui_taCooldownTemp;
lv_obj_t * ui_Panel31;
lv_obj_t * ui_LabelPreheat19;
void ui_event_taCooldownDur(lv_event_t * e);
lv_obj_t * ui_taCooldownDur;
void ui_event_Keyboard2(lv_event_t * e);
lv_obj_t * ui_Keyboard2;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_settings[1] = {&ui_img_settings2_png};
const lv_img_dsc_t * ui_imgset_watch[2] = {&ui_img_watch2_png, &ui_img_watch3_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Load_Profile(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        EV_Load_Profile_From_Flash(e);
    }
}

void ui_event_BuCloseLoadProfile(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Reflow_Oven, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Reflow_Oven_screen_init);
    }
}

void ui_event_BuSettingsProfile1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EV_Show_Profile_Settings(e);
    }
}

void ui_event_BuSelectProfile1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EV_Select_Saved_Profile(e);
    }
}

void ui_event_Label34(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EV_(e);
    }
}

void ui_event_BuSettingsProfile2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EV_Show_Profile_Settings(e);
    }
}

void ui_event_BuSelectProfile2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EV_Select_Saved_Profile(e);
    }
}

void ui_event_BuSettingsProfile3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EV_Show_Profile_Settings(e);
    }
}

void ui_event_BuSelectProfile3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EV_Select_Saved_Profile(e);
    }
}

void ui_event_BuSettingsProfile4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EV_Show_Profile_Settings(e);
    }
}

void ui_event_BuSelectProfile4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EV_Select_Saved_Profile(e);
    }
}

void ui_event_BuSettingsProfile5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EV_Show_Profile_Settings(e);
    }
}

void ui_event_BuSelectProfile5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EV_Select_Saved_Profile(e);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EV_Start_Reflow(e);
    }
}

void ui_event_BuNewProfile(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_New_Profile, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_New_Profile_screen_init);
    }
}

void ui_event_BuLoadProfile(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Load_Profile, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Load_Profile_screen_init);
    }
}

void ui_event_BuCloseNewProfile(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Reflow_Oven, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Reflow_Oven_screen_init);
    }
}

void ui_event_taProfileName(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EV_Set_Keyboard_Mode(e);
    }
}

void ui_event_taPreheatTempRise(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EV_Set_Keyboard_Mode(e);
    }
}

void ui_event_taSoakTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EV_Set_Keyboard_Mode(e);
    }
}

void ui_event_taSoakDur(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EV_Set_Keyboard_Mode(e);
    }
}

void ui_event_taRampUpTempRise(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EV_Set_Keyboard_Mode(e);
    }
}

void ui_event_taReflowTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EV_Set_Keyboard_Mode(e);
    }
}

void ui_event_taReflowDur(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EV_Set_Keyboard_Mode(e);
    }
}

void ui_event_taCooldownTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EV_Set_Keyboard_Mode(e);
    }
}

void ui_event_taCooldownDur(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EV_Set_Keyboard_Mode(e);
    }
}

void ui_event_Keyboard2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        EV_Key_Enter(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Load_Profile_screen_init();
    ui_Reflow_Oven_screen_init();
    ui_New_Profile_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Load_Profile);
}
