// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "profile_management.h"
#include <stdio.h>
#include "custom_ui.h"
#include "reflowOvenControl.h"

void EV_Key_Enter(lv_event_t * e)
{
	// Your code here
	ReflowProfile saveNewProfile;
	strcpy(saveNewProfile.profile_Name,lv_textarea_get_text(ui_taProfileName));
	saveNewProfile.preheat_tempRise = atoi(lv_textarea_get_text(ui_taPreheatTempRise));
	saveNewProfile.soak_temp = atoi(lv_textarea_get_text(ui_taSoakTemp));
	saveNewProfile.soak_duration = atoi(lv_textarea_get_text(ui_taSoakDur));
	saveNewProfile.rampPeak_TempRise = atoi(lv_textarea_get_text(ui_taRampUpTempRise));
	saveNewProfile.reflow_temp = atoi(lv_textarea_get_text(ui_taReflowTemp));
	saveNewProfile.reflow_duration = atoi(lv_textarea_get_text(ui_taReflowDur));
	saveNewProfile.cooldown_temp = atoi(lv_textarea_get_text(ui_taCooldownTemp));
	saveNewProfile.cooldown_duration = atoi(lv_textarea_get_text(ui_taCooldownDur));
	
	// 🔍 Check if the profile already exists
	if (profileExists(saveNewProfile.profile_Name)) { 
		overwriteProfile(saveNewProfile);
	} else {
		if (!saveProfile(saveNewProfile)) {
			lv_label_set_text(ui_LabelPreheat5, "Error Saving");
		}
	}


	char temp_str[40];  // Buffer to hold the string representation
	snprintf(temp_str, sizeof(temp_str), "Soldering Phases: (%s)", saveNewProfile.profile_Name);
	lv_label_set_text(ui_LaMenuTitle,temp_str);

	snprintf(temp_str, sizeof(temp_str), "Temperatur: %d °/s", saveNewProfile.preheat_tempRise);
	lv_label_set_text(ui_laPreheatTempRise,temp_str);

	snprintf(temp_str, sizeof(temp_str), "Temperatur: %d °C", saveNewProfile.soak_temp);
	lv_label_set_text(ui_laSoakTemp,temp_str);

	snprintf(temp_str, sizeof(temp_str), "Duration: %d min", saveNewProfile.soak_duration);
	lv_label_set_text(ui_laSoakDur,temp_str);

	snprintf(temp_str, sizeof(temp_str), "Rate: %d °/s", saveNewProfile.rampPeak_TempRise);
	lv_label_set_text(ui_laRampPeakTempRise,temp_str);

	snprintf(temp_str, sizeof(temp_str), "Temperatur: %d °C", saveNewProfile.reflow_temp);
	lv_label_set_text(ui_laReflowTemp, temp_str);

	snprintf(temp_str, sizeof(temp_str), "Duration: %d min", saveNewProfile.reflow_duration);
	lv_label_set_text(ui_laReflowDur, temp_str);

	snprintf(temp_str, sizeof(temp_str), "Temperatur: %d °C", saveNewProfile.cooldown_temp);
	lv_label_set_text(ui_laCooldownTemp, temp_str);

	snprintf(temp_str, sizeof(temp_str), "Duration: %d min", saveNewProfile.cooldown_duration);
	lv_label_set_text(ui_laCooldownDur, temp_str);


	
	addTemperatureProfileToChart(saveNewProfile);

	// Save choosen Reflow Profile to global variable
	setActiveReflowOvenProfile(saveNewProfile);

	_ui_screen_change(&ui_Reflow_Oven, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Reflow_Oven_screen_init);
	
}

void EV_Start_Reflow(lv_event_t * e)
{
	// Your code here
	startReflowProcess = !startReflowProcess;

	setStartButtonBakgroundColor(startReflowProcess);
}

void EV_Set_Keyboard_Mode(lv_event_t * e)
{
	lv_obj_t * ta = lv_event_get_target(e);  // Get the textarea that triggered the event

	if(ta == ui_taProfileName) {
        lv_keyboard_set_mode(ui_Keyboard2, LV_KEYBOARD_MODE_TEXT_LOWER);
    } else {
        lv_keyboard_set_mode(ui_Keyboard2, LV_KEYBOARD_MODE_NUMBER);
    }

	 // Set the triggered textarea as the active one for the keyboard
	 lv_keyboard_set_textarea(ui_Keyboard2, ta);
}

void EV_Load_Profile_From_Flash(lv_event_t * e)
{
	lv_obj_t* profile_labels[] = {ui_laProfile1, ui_laProfile2, ui_laProfile3, ui_laProfile4, ui_laProfile5};
	lv_obj_t* profile_panels[] = {ui_PanelProfile1, ui_PanelProfile2, ui_PanelProfile3, ui_PanelProfile4, ui_PanelProfile5};

	const int PROFILE_COUNT = getProfileCount();

	// Set Visibility of Panels
	for (int index = 0; index < PROFILE_COUNT; index++)
	{
		lv_obj_clear_flag(profile_panels[index], LV_OBJ_FLAG_HIDDEN);
	}
	for (int index = PROFILE_COUNT; index < 5; index++)
	{
		lv_obj_add_flag(profile_panels[index], LV_OBJ_FLAG_HIDDEN);
	}

	// Print Profiles
	ReflowProfile reflowProfile;
	for(int i=0; i<PROFILE_COUNT; i++) {
		bool status = getProfile(&reflowProfile,i);
		if (status != true) {
			char count_str[] = "error"; // Allocate space for the string (adjust size as needed)
			//snprintf(count_str, sizeof(count_str), "%d", "getProfileCount()"); // Convert integer to string
			lv_label_set_text(profile_labels[i],count_str);
		} else {
			lv_label_set_text(profile_labels[i],reflowProfile.profile_Name);
		}
	}
}

void EV_Show_Profile_Settings(lv_event_t * e)
{	
	lv_obj_t * ta = lv_event_get_target(e);

	ReflowProfile reflowProfile;
	bool status = false;
	if(ta == ui_BuSettingsProfile1) {
		status = getProfile(&reflowProfile,0);
	} else if(ta == ui_BuSettingsProfile2) {
		status = getProfile(&reflowProfile,1);
	} else if(ta == ui_BuSettingsProfile3) {
		status = getProfile(&reflowProfile,2);
	} else if(ta == ui_BuSettingsProfile4) {
		status = getProfile(&reflowProfile,3);
	} else if(ta == ui_BuSettingsProfile5) {
		status = getProfile(&reflowProfile,4);
	}

	lv_textarea_set_text(ui_taProfileName,reflowProfile.profile_Name);

	char temp_str[20];  // Buffer to hold the string representation
	snprintf(temp_str, sizeof(temp_str), "%d", reflowProfile.preheat_tempRise);
	lv_textarea_set_text(ui_taPreheatTempRise,temp_str);

	snprintf(temp_str, sizeof(temp_str), "%d", reflowProfile.soak_temp);
	lv_textarea_set_text(ui_taSoakTemp,temp_str);

	snprintf(temp_str, sizeof(temp_str), "%d", reflowProfile.soak_duration);
	lv_textarea_set_text(ui_taSoakDur,temp_str);

	snprintf(temp_str, sizeof(temp_str), "%d", reflowProfile.rampPeak_TempRise);
	lv_textarea_set_text(ui_taRampUpTempRise,temp_str);

	snprintf(temp_str, sizeof(temp_str), "%d", reflowProfile.reflow_temp);
	lv_textarea_set_text(ui_taReflowTemp, temp_str);

	snprintf(temp_str, sizeof(temp_str), "%d", reflowProfile.reflow_duration);
	lv_textarea_set_text(ui_taReflowDur, temp_str);

	snprintf(temp_str, sizeof(temp_str), "%d", reflowProfile.cooldown_temp);
	lv_textarea_set_text(ui_taCooldownTemp, temp_str);

	snprintf(temp_str, sizeof(temp_str), "%d", reflowProfile.cooldown_duration);
	lv_textarea_set_text(ui_taCooldownDur, temp_str);

	_ui_screen_change(&ui_New_Profile, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_New_Profile_screen_init);
}

void EV_Select_Saved_Profile(lv_event_t * e)
{
	// Your code here
	lv_obj_t* profile_buttons[] = {ui_BuSelectProfile1, ui_BuSelectProfile2, ui_BuSelectProfile3, ui_BuSelectProfile4, ui_BuSelectProfile5};
	lv_obj_t * ta = lv_event_get_target(e);  // Get the textarea that triggered the event

	ReflowProfile reflowProfile;
	bool status = false;
	if(ta == ui_BuSelectProfile1) {
		status = getProfile(&reflowProfile,0);
	} else if(ta == ui_BuSelectProfile2) {
		status = getProfile(&reflowProfile,1);
	} else if(ta == ui_BuSelectProfile3) {
		status = getProfile(&reflowProfile,2);
	} else if(ta == ui_BuSelectProfile4) {
		status = getProfile(&reflowProfile,3);
	} else if(ta == ui_BuSelectProfile5) {
		status = getProfile(&reflowProfile,4);
	}

	char temp_str[40];  // Buffer to hold the string representation
	snprintf(temp_str, sizeof(temp_str), "Soldering Phases: (%s)", reflowProfile.profile_Name);
	lv_label_set_text(ui_LaMenuTitle,temp_str);

	snprintf(temp_str, sizeof(temp_str), "Temperatur: %d °/s", reflowProfile.preheat_tempRise);
	lv_label_set_text(ui_laPreheatTempRise,temp_str);

	snprintf(temp_str, sizeof(temp_str), "Temperatur: %d °C", reflowProfile.soak_temp);
	lv_label_set_text(ui_laSoakTemp,temp_str);

	snprintf(temp_str, sizeof(temp_str), "Duration: %d sec", reflowProfile.soak_duration);
	lv_label_set_text(ui_laSoakDur,temp_str);

	snprintf(temp_str, sizeof(temp_str), "Rate: %d °/s", reflowProfile.rampPeak_TempRise);
	lv_label_set_text(ui_laRampPeakTempRise,temp_str);

	snprintf(temp_str, sizeof(temp_str), "Temperatur: %d °C", reflowProfile.reflow_temp);
	lv_label_set_text(ui_laReflowTemp, temp_str);

	snprintf(temp_str, sizeof(temp_str), "Duration: %d sec", reflowProfile.reflow_duration);
	lv_label_set_text(ui_laReflowDur, temp_str);

	snprintf(temp_str, sizeof(temp_str), "Temperatur: %d °C", reflowProfile.cooldown_temp);
	lv_label_set_text(ui_laCooldownTemp, temp_str);

	snprintf(temp_str, sizeof(temp_str), "Duration: %d sec", reflowProfile.cooldown_duration);
	lv_label_set_text(ui_laCooldownDur, temp_str);

	addTemperatureProfileToChart(reflowProfile);
	setActiveReflowOvenProfile(reflowProfile);
}

void EV_(lv_event_t * e)
{
	// Your code here
}
