// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void EV_Load_Profile_From_Flash(lv_event_t * e);
void EV_Show_Profile_Settings(lv_event_t * e);
void EV_Select_Saved_Profile(lv_event_t * e);
void EV_(lv_event_t * e);
void EV_Start_Reflow(lv_event_t * e);
void EV_Set_Keyboard_Mode(lv_event_t * e);
void EV_Key_Enter(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
