// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Load_Profile_screen_init(void)
{
    ui_Load_Profile = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Load_Profile, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Load_Profile, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Load_Profile, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Load_Profile, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Load_Profile, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Load_Profile, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Load_Profile, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel14 = lv_obj_create(ui_Load_Profile);
    lv_obj_set_width(ui_Panel14, 450);
    lv_obj_set_height(ui_Panel14, 40);
    lv_obj_set_x(ui_Panel14, 32);
    lv_obj_set_y(ui_Panel14, -1);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel14, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel14, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel14, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel14, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x15171A), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_Panel14);
    lv_img_set_src(ui_Image6, &ui_img_fire_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 21
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_Image6, -210);
    lv_obj_set_y(ui_Image6, -200);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 280);

    ui_Label4 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_Label4, -116);
    lv_obj_set_y(ui_Label4, -200);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Choose a Profile                               ");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BuCloseLoadProfile = lv_btn_create(ui_Panel14);
    lv_obj_set_width(ui_BuCloseLoadProfile, 50);
    lv_obj_set_height(ui_BuCloseLoadProfile, 50);
    lv_obj_set_align(ui_BuCloseLoadProfile, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BuCloseLoadProfile, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BuCloseLoadProfile, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BuCloseLoadProfile, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BuCloseLoadProfile, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BuCloseLoadProfile, &ui_img_close_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel39 = lv_obj_create(ui_Load_Profile);
    lv_obj_set_width(ui_Panel39, 450);
    lv_obj_set_height(ui_Panel39, 730);
    lv_obj_set_x(ui_Panel39, -175);
    lv_obj_set_y(ui_Panel39, -3);
    lv_obj_set_align(ui_Panel39, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel39, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel39, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Panel39, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel39, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel39, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel39, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel39, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel39, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelProfile1 = lv_obj_create(ui_Panel39);
    lv_obj_set_width(ui_PanelProfile1, 430);
    lv_obj_set_height(ui_PanelProfile1, 90);
    lv_obj_set_x(ui_PanelProfile1, 1);
    lv_obj_set_y(ui_PanelProfile1, 48);
    lv_obj_set_align(ui_PanelProfile1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelProfile1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelProfile1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelProfile1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelProfile1, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelProfile1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelProfile1, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelProfile1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelProfile1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelProfile1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelProfile1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelProfile1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelProfile1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPreheat2 = lv_obj_create(ui_PanelProfile1);
    lv_obj_set_width(ui_PanelPreheat2, 180);
    lv_obj_set_height(ui_PanelPreheat2, 90);
    lv_obj_set_x(ui_PanelPreheat2, -29);
    lv_obj_set_y(ui_PanelPreheat2, -108);
    lv_obj_set_align(ui_PanelPreheat2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelPreheat2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelPreheat2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelPreheat2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPreheat2, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPreheat2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPreheat2, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPreheat2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelPreheat2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelPreheat2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelPreheat2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelPreheat2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPreheat20 = lv_label_create(ui_PanelPreheat2);
    lv_obj_set_width(ui_LabelPreheat20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreheat20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreheat20, -140);
    lv_obj_set_y(ui_LabelPreheat20, -132);
    lv_obj_set_align(ui_LabelPreheat20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreheat20, "Profile 1");
    lv_obj_set_style_text_align(ui_LabelPreheat20, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPreheat20, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_laProfile1 = lv_label_create(ui_PanelPreheat2);
    lv_obj_set_width(ui_laProfile1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_laProfile1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_laProfile1, -150);
    lv_obj_set_y(ui_laProfile1, -104);
    lv_obj_set_align(ui_laProfile1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_laProfile1, "SMD291AX");
    lv_obj_set_style_text_align(ui_laProfile1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_laProfile1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel41 = lv_obj_create(ui_PanelProfile1);
    lv_obj_set_width(ui_Panel41, 226);
    lv_obj_set_height(ui_Panel41, 90);
    lv_obj_set_x(ui_Panel41, -112);
    lv_obj_set_y(ui_Panel41, 26);
    lv_obj_set_align(ui_Panel41, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel41, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel41, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel41, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel41, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel41, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BuSettingsProfile1 = lv_btn_create(ui_Panel41);
    lv_obj_set_width(ui_BuSettingsProfile1, 50);
    lv_obj_set_height(ui_BuSettingsProfile1, 50);
    lv_obj_set_align(ui_BuSettingsProfile1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BuSettingsProfile1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BuSettingsProfile1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BuSettingsProfile1, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BuSettingsProfile1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BuSettingsProfile1, &ui_img_settings_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BuSelectProfile1 = lv_btn_create(ui_Panel41);
    lv_obj_set_width(ui_BuSelectProfile1, 160);
    lv_obj_set_height(ui_BuSelectProfile1, 40);
    lv_obj_set_x(ui_BuSelectProfile1, -117);
    lv_obj_set_y(ui_BuSelectProfile1, 360);
    lv_obj_set_align(ui_BuSelectProfile1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BuSelectProfile1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BuSelectProfile1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_BuSelectProfile1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BuSelectProfile1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BuSelectProfile1, lv_color_hex(0x1879FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BuSelectProfile1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_BuSelectProfile1);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, -122);
    lv_obj_set_y(ui_Label34, 361);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "Select");

    ui_PanelProfile2 = lv_obj_create(ui_Panel39);
    lv_obj_set_width(ui_PanelProfile2, 430);
    lv_obj_set_height(ui_PanelProfile2, 90);
    lv_obj_set_x(ui_PanelProfile2, 1);
    lv_obj_set_y(ui_PanelProfile2, 48);
    lv_obj_set_align(ui_PanelProfile2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelProfile2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelProfile2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelProfile2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelProfile2, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelProfile2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelProfile2, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelProfile2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelProfile2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelProfile2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelProfile2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelProfile2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelProfile2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPreheat1 = lv_obj_create(ui_PanelProfile2);
    lv_obj_set_width(ui_PanelPreheat1, 180);
    lv_obj_set_height(ui_PanelPreheat1, 90);
    lv_obj_set_x(ui_PanelPreheat1, -29);
    lv_obj_set_y(ui_PanelPreheat1, -108);
    lv_obj_set_align(ui_PanelPreheat1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelPreheat1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelPreheat1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelPreheat1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPreheat1, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPreheat1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPreheat1, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPreheat1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelPreheat1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelPreheat1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelPreheat1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelPreheat1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPreheat2 = lv_label_create(ui_PanelPreheat1);
    lv_obj_set_width(ui_LabelPreheat2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreheat2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreheat2, -140);
    lv_obj_set_y(ui_LabelPreheat2, -132);
    lv_obj_set_align(ui_LabelPreheat2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreheat2, "Profile 2");
    lv_obj_set_style_text_align(ui_LabelPreheat2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPreheat2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_laProfile2 = lv_label_create(ui_PanelPreheat1);
    lv_obj_set_width(ui_laProfile2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_laProfile2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_laProfile2, -150);
    lv_obj_set_y(ui_laProfile2, -104);
    lv_obj_set_align(ui_laProfile2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_laProfile2, "SC 170");
    lv_obj_set_style_text_align(ui_laProfile2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_laProfile2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel26 = lv_obj_create(ui_PanelProfile2);
    lv_obj_set_width(ui_Panel26, 226);
    lv_obj_set_height(ui_Panel26, 90);
    lv_obj_set_x(ui_Panel26, -112);
    lv_obj_set_y(ui_Panel26, 26);
    lv_obj_set_align(ui_Panel26, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel26, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel26, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel26, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel26, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BuSettingsProfile2 = lv_btn_create(ui_Panel26);
    lv_obj_set_width(ui_BuSettingsProfile2, 50);
    lv_obj_set_height(ui_BuSettingsProfile2, 50);
    lv_obj_set_align(ui_BuSettingsProfile2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BuSettingsProfile2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BuSettingsProfile2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BuSettingsProfile2, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BuSettingsProfile2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BuSettingsProfile2, &ui_img_settings_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BuSelectProfile2 = lv_btn_create(ui_Panel26);
    lv_obj_set_width(ui_BuSelectProfile2, 160);
    lv_obj_set_height(ui_BuSelectProfile2, 40);
    lv_obj_set_x(ui_BuSelectProfile2, -117);
    lv_obj_set_y(ui_BuSelectProfile2, 360);
    lv_obj_set_align(ui_BuSelectProfile2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BuSelectProfile2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BuSelectProfile2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_BuSelectProfile2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BuSelectProfile2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BuSelectProfile2, lv_color_hex(0x1879FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BuSelectProfile2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_BuSelectProfile2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -122);
    lv_obj_set_y(ui_Label10, 361);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Select");

    ui_PanelProfile3 = lv_obj_create(ui_Panel39);
    lv_obj_set_width(ui_PanelProfile3, 430);
    lv_obj_set_height(ui_PanelProfile3, 90);
    lv_obj_set_x(ui_PanelProfile3, 1);
    lv_obj_set_y(ui_PanelProfile3, 48);
    lv_obj_set_align(ui_PanelProfile3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelProfile3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelProfile3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelProfile3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelProfile3, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelProfile3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelProfile3, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelProfile3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelProfile3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelProfile3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelProfile3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelProfile3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelProfile3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPreheat3 = lv_obj_create(ui_PanelProfile3);
    lv_obj_set_width(ui_PanelPreheat3, 180);
    lv_obj_set_height(ui_PanelPreheat3, 90);
    lv_obj_set_x(ui_PanelPreheat3, -29);
    lv_obj_set_y(ui_PanelPreheat3, -108);
    lv_obj_set_align(ui_PanelPreheat3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelPreheat3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelPreheat3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelPreheat3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPreheat3, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPreheat3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPreheat3, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPreheat3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelPreheat3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelPreheat3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelPreheat3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelPreheat3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPreheat21 = lv_label_create(ui_PanelPreheat3);
    lv_obj_set_width(ui_LabelPreheat21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreheat21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreheat21, -140);
    lv_obj_set_y(ui_LabelPreheat21, -132);
    lv_obj_set_align(ui_LabelPreheat21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreheat21, "Profile 3");
    lv_obj_set_style_text_align(ui_LabelPreheat21, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPreheat21, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_laProfile3 = lv_label_create(ui_PanelPreheat3);
    lv_obj_set_width(ui_laProfile3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_laProfile3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_laProfile3, -150);
    lv_obj_set_y(ui_laProfile3, -104);
    lv_obj_set_align(ui_laProfile3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_laProfile3, "Sn42bi58");
    lv_obj_set_style_text_align(ui_laProfile3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_laProfile3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel43 = lv_obj_create(ui_PanelProfile3);
    lv_obj_set_width(ui_Panel43, 226);
    lv_obj_set_height(ui_Panel43, 90);
    lv_obj_set_x(ui_Panel43, -112);
    lv_obj_set_y(ui_Panel43, 26);
    lv_obj_set_align(ui_Panel43, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel43, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel43, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel43, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel43, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel43, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BuSettingsProfile3 = lv_btn_create(ui_Panel43);
    lv_obj_set_width(ui_BuSettingsProfile3, 50);
    lv_obj_set_height(ui_BuSettingsProfile3, 50);
    lv_obj_set_align(ui_BuSettingsProfile3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BuSettingsProfile3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BuSettingsProfile3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BuSettingsProfile3, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BuSettingsProfile3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BuSettingsProfile3, &ui_img_settings_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BuSelectProfile3 = lv_btn_create(ui_Panel43);
    lv_obj_set_width(ui_BuSelectProfile3, 160);
    lv_obj_set_height(ui_BuSelectProfile3, 40);
    lv_obj_set_x(ui_BuSelectProfile3, -117);
    lv_obj_set_y(ui_BuSelectProfile3, 360);
    lv_obj_set_align(ui_BuSelectProfile3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BuSelectProfile3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BuSelectProfile3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_BuSelectProfile3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BuSelectProfile3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BuSelectProfile3, lv_color_hex(0x1879FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BuSelectProfile3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_BuSelectProfile3);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -122);
    lv_obj_set_y(ui_Label13, 361);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Select");

    ui_PanelProfile4 = lv_obj_create(ui_Panel39);
    lv_obj_set_width(ui_PanelProfile4, 430);
    lv_obj_set_height(ui_PanelProfile4, 90);
    lv_obj_set_x(ui_PanelProfile4, 1);
    lv_obj_set_y(ui_PanelProfile4, 48);
    lv_obj_set_align(ui_PanelProfile4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelProfile4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelProfile4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelProfile4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelProfile4, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelProfile4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelProfile4, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelProfile4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelProfile4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelProfile4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelProfile4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelProfile4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelProfile4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPreheat4 = lv_obj_create(ui_PanelProfile4);
    lv_obj_set_width(ui_PanelPreheat4, 180);
    lv_obj_set_height(ui_PanelPreheat4, 90);
    lv_obj_set_x(ui_PanelPreheat4, -29);
    lv_obj_set_y(ui_PanelPreheat4, -108);
    lv_obj_set_align(ui_PanelPreheat4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelPreheat4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelPreheat4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelPreheat4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPreheat4, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPreheat4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPreheat4, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPreheat4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelPreheat4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelPreheat4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelPreheat4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelPreheat4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPreheat22 = lv_label_create(ui_PanelPreheat4);
    lv_obj_set_width(ui_LabelPreheat22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreheat22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreheat22, -140);
    lv_obj_set_y(ui_LabelPreheat22, -132);
    lv_obj_set_align(ui_LabelPreheat22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreheat22, "Profile 4");
    lv_obj_set_style_text_align(ui_LabelPreheat22, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPreheat22, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_laProfile4 = lv_label_create(ui_PanelPreheat4);
    lv_obj_set_width(ui_laProfile4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_laProfile4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_laProfile4, -150);
    lv_obj_set_y(ui_laProfile4, -104);
    lv_obj_set_align(ui_laProfile4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_laProfile4, "..........");
    lv_obj_set_style_text_align(ui_laProfile4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_laProfile4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel45 = lv_obj_create(ui_PanelProfile4);
    lv_obj_set_width(ui_Panel45, 226);
    lv_obj_set_height(ui_Panel45, 90);
    lv_obj_set_x(ui_Panel45, -112);
    lv_obj_set_y(ui_Panel45, 26);
    lv_obj_set_align(ui_Panel45, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel45, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel45, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel45, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel45, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel45, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel45, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel45, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BuSettingsProfile4 = lv_btn_create(ui_Panel45);
    lv_obj_set_width(ui_BuSettingsProfile4, 50);
    lv_obj_set_height(ui_BuSettingsProfile4, 50);
    lv_obj_set_align(ui_BuSettingsProfile4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BuSettingsProfile4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BuSettingsProfile4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BuSettingsProfile4, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BuSettingsProfile4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BuSettingsProfile4, &ui_img_settings_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BuSelectProfile4 = lv_btn_create(ui_Panel45);
    lv_obj_set_width(ui_BuSelectProfile4, 160);
    lv_obj_set_height(ui_BuSelectProfile4, 40);
    lv_obj_set_x(ui_BuSelectProfile4, -117);
    lv_obj_set_y(ui_BuSelectProfile4, 360);
    lv_obj_set_align(ui_BuSelectProfile4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BuSelectProfile4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BuSelectProfile4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_BuSelectProfile4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BuSelectProfile4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BuSelectProfile4, lv_color_hex(0x1879FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BuSelectProfile4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_BuSelectProfile4);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -122);
    lv_obj_set_y(ui_Label8, 361);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Select");

    ui_PanelProfile5 = lv_obj_create(ui_Panel39);
    lv_obj_set_width(ui_PanelProfile5, 430);
    lv_obj_set_height(ui_PanelProfile5, 90);
    lv_obj_set_x(ui_PanelProfile5, 1);
    lv_obj_set_y(ui_PanelProfile5, 48);
    lv_obj_set_align(ui_PanelProfile5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelProfile5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelProfile5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelProfile5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelProfile5, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelProfile5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelProfile5, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelProfile5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelProfile5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelProfile5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelProfile5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelProfile5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelProfile5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPreheat10 = lv_obj_create(ui_PanelProfile5);
    lv_obj_set_width(ui_PanelPreheat10, 180);
    lv_obj_set_height(ui_PanelPreheat10, 90);
    lv_obj_set_x(ui_PanelPreheat10, -29);
    lv_obj_set_y(ui_PanelPreheat10, -108);
    lv_obj_set_align(ui_PanelPreheat10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelPreheat10, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelPreheat10, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelPreheat10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPreheat10, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPreheat10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPreheat10, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPreheat10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelPreheat10, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelPreheat10, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelPreheat10, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelPreheat10, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPreheat23 = lv_label_create(ui_PanelPreheat10);
    lv_obj_set_width(ui_LabelPreheat23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreheat23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreheat23, -140);
    lv_obj_set_y(ui_LabelPreheat23, -132);
    lv_obj_set_align(ui_LabelPreheat23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreheat23, "Profile 5");
    lv_obj_set_style_text_align(ui_LabelPreheat23, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPreheat23, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_laProfile5 = lv_label_create(ui_PanelPreheat10);
    lv_obj_set_width(ui_laProfile5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_laProfile5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_laProfile5, -150);
    lv_obj_set_y(ui_laProfile5, -104);
    lv_obj_set_align(ui_laProfile5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_laProfile5, "..........");
    lv_obj_set_style_text_align(ui_laProfile5, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_laProfile5, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel47 = lv_obj_create(ui_PanelProfile5);
    lv_obj_set_width(ui_Panel47, 226);
    lv_obj_set_height(ui_Panel47, 90);
    lv_obj_set_x(ui_Panel47, -112);
    lv_obj_set_y(ui_Panel47, 26);
    lv_obj_set_align(ui_Panel47, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel47, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel47, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel47, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel47, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel47, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel47, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel47, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BuSettingsProfile5 = lv_btn_create(ui_Panel47);
    lv_obj_set_width(ui_BuSettingsProfile5, 50);
    lv_obj_set_height(ui_BuSettingsProfile5, 50);
    lv_obj_set_align(ui_BuSettingsProfile5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BuSettingsProfile5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BuSettingsProfile5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BuSettingsProfile5, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BuSettingsProfile5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BuSettingsProfile5, &ui_img_settings_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BuSelectProfile5 = lv_btn_create(ui_Panel47);
    lv_obj_set_width(ui_BuSelectProfile5, 160);
    lv_obj_set_height(ui_BuSelectProfile5, 40);
    lv_obj_set_x(ui_BuSelectProfile5, -117);
    lv_obj_set_y(ui_BuSelectProfile5, 360);
    lv_obj_set_align(ui_BuSelectProfile5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BuSelectProfile5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BuSelectProfile5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_BuSelectProfile5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BuSelectProfile5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BuSelectProfile5, lv_color_hex(0x1879FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BuSelectProfile5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_BuSelectProfile5);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -122);
    lv_obj_set_y(ui_Label11, 361);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Select");

    lv_obj_add_event_cb(ui_BuCloseLoadProfile, ui_event_BuCloseLoadProfile, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BuSettingsProfile1, ui_event_BuSettingsProfile1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label34, ui_event_Label34, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BuSelectProfile1, ui_event_BuSelectProfile1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BuSettingsProfile2, ui_event_BuSettingsProfile2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BuSelectProfile2, ui_event_BuSelectProfile2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BuSettingsProfile3, ui_event_BuSettingsProfile3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BuSelectProfile3, ui_event_BuSelectProfile3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BuSettingsProfile4, ui_event_BuSettingsProfile4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BuSelectProfile4, ui_event_BuSelectProfile4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BuSettingsProfile5, ui_event_BuSettingsProfile5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BuSelectProfile5, ui_event_BuSelectProfile5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Load_Profile, ui_event_Load_Profile, LV_EVENT_ALL, NULL);
    uic_Panel1 = ui_PanelPreheat2;
    uic_Panel1 = ui_PanelPreheat1;
    uic_Panel1 = ui_PanelPreheat3;
    uic_Panel1 = ui_PanelPreheat4;
    uic_Panel1 = ui_PanelPreheat10;

}
