// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_New_Profile_screen_init(void)
{
    ui_New_Profile = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_New_Profile, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_New_Profile, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_New_Profile, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_New_Profile, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_New_Profile, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_New_Profile, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_New_Profile, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_New_Profile, lv_color_hex(0x101418), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_New_Profile, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Panel38 = lv_obj_create(ui_New_Profile);
    lv_obj_set_width(ui_Panel38, 450);
    lv_obj_set_height(ui_Panel38, 40);
    lv_obj_set_align(ui_Panel38, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel38, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel38, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel38, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel38, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel38, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel38, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel38, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel38, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel38, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_img_create(ui_Panel38);
    lv_img_set_src(ui_Image10, &ui_img_fire_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 21
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_Image10, -210);
    lv_obj_set_y(ui_Image10, -200);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image10, 280);

    ui_Label3 = lv_label_create(ui_Panel38);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Save new Profile                              ");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BuCloseNewProfile = lv_btn_create(ui_Panel38);
    lv_obj_set_width(ui_BuCloseNewProfile, 50);
    lv_obj_set_height(ui_BuCloseNewProfile, 50);
    lv_obj_set_align(ui_BuCloseNewProfile, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BuCloseNewProfile, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BuCloseNewProfile, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BuCloseNewProfile, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BuCloseNewProfile, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BuCloseNewProfile, &ui_img_close_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel15 = lv_obj_create(ui_New_Profile);
    lv_obj_set_width(ui_Panel15, 450);
    lv_obj_set_height(ui_Panel15, 520);
    lv_obj_set_x(ui_Panel15, 21);
    lv_obj_set_y(ui_Panel15, -148);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel15, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel15, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_Panel15, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel15, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel15, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel37 = lv_obj_create(ui_Panel15);
    lv_obj_set_width(ui_Panel37, 440);
    lv_obj_set_height(ui_Panel37, 120);
    lv_obj_set_align(ui_Panel37, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel37, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel37, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel37, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel37, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel37, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_Panel37);
    lv_obj_set_width(ui_Panel16, 420);
    lv_obj_set_height(ui_Panel16, 40);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel16, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel16, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel16, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panel16);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Profile Name");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_taProfileName = lv_textarea_create(ui_Panel37);
    lv_obj_set_width(ui_taProfileName, 420);
    lv_obj_set_height(ui_taProfileName, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_taProfileName, 0);
    lv_obj_set_y(ui_taProfileName, -13);
    lv_obj_set_align(ui_taProfileName, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_taProfileName, 9);
    lv_textarea_set_placeholder_text(ui_taProfileName, "eg. SMD291AX");
    lv_textarea_set_one_line(ui_taProfileName, true);
    lv_obj_set_style_text_color(ui_taProfileName, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_taProfileName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_taProfileName, lv_color_hex(0xF7F2F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_taProfileName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_taProfileName, lv_color_hex(0x1879FF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_taProfileName, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Panel32 = lv_obj_create(ui_Panel15);
    lv_obj_set_width(ui_Panel32, 440);
    lv_obj_set_height(ui_Panel32, 140);
    lv_obj_set_align(ui_Panel32, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel32, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel32, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel32, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel32, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel17 = lv_obj_create(ui_Panel32);
    lv_obj_set_width(ui_Panel17, 420);
    lv_obj_set_height(ui_Panel17, 40);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel17, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel17, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel17, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPreheat1 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_LabelPreheat1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreheat1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreheat1, -123);
    lv_obj_set_y(ui_LabelPreheat1, -291);
    lv_obj_set_align(ui_LabelPreheat1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreheat1, "Phase 1: Preheat");
    lv_obj_set_style_text_font(ui_LabelPreheat1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel18 = lv_obj_create(ui_Panel32);
    lv_obj_set_width(ui_Panel18, 420);
    lv_obj_set_height(ui_Panel18, 80);
    lv_obj_set_align(ui_Panel18, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel18, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel18, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel18, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPreheat3 = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_LabelPreheat3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreheat3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreheat3, -123);
    lv_obj_set_y(ui_LabelPreheat3, -291);
    lv_obj_set_align(ui_LabelPreheat3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreheat3, "Temperature rise (°C/s)");
    lv_obj_set_style_text_align(ui_LabelPreheat3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPreheat3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_taPreheatTempRise = lv_textarea_create(ui_Panel18);
    lv_obj_set_width(ui_taPreheatTempRise, 420);
    lv_obj_set_height(ui_taPreheatTempRise, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_taPreheatTempRise, 0);
    lv_obj_set_y(ui_taPreheatTempRise, -13);
    lv_obj_set_align(ui_taPreheatTempRise, LV_ALIGN_CENTER);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_taPreheatTempRise, NULL);
    else lv_textarea_set_accepted_chars(ui_taPreheatTempRise, "0123456789");
    lv_textarea_set_placeholder_text(ui_taPreheatTempRise, "eg. 4");
    lv_textarea_set_one_line(ui_taPreheatTempRise, true);
    lv_obj_set_style_text_color(ui_taPreheatTempRise, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_taPreheatTempRise, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_taPreheatTempRise, lv_color_hex(0xF7F2F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_taPreheatTempRise, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_taPreheatTempRise, lv_color_hex(0x1879FF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_taPreheatTempRise, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Panel33 = lv_obj_create(ui_Panel15);
    lv_obj_set_width(ui_Panel33, 440);
    lv_obj_set_height(ui_Panel33, 240);
    lv_obj_set_align(ui_Panel33, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel33, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel33, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel33, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel33, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel25 = lv_obj_create(ui_Panel33);
    lv_obj_set_width(ui_Panel25, 420);
    lv_obj_set_height(ui_Panel25, 40);
    lv_obj_set_align(ui_Panel25, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel25, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel25, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel25, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel25, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPreheat14 = lv_label_create(ui_Panel25);
    lv_obj_set_width(ui_LabelPreheat14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreheat14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreheat14, -123);
    lv_obj_set_y(ui_LabelPreheat14, -291);
    lv_obj_set_align(ui_LabelPreheat14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreheat14, "Phase 2: Soak");
    lv_obj_set_style_text_font(ui_LabelPreheat14, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel21 = lv_obj_create(ui_Panel33);
    lv_obj_set_width(ui_Panel21, 420);
    lv_obj_set_height(ui_Panel21, 80);
    lv_obj_set_align(ui_Panel21, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel21, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel21, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel21, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel21, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPreheat4 = lv_label_create(ui_Panel21);
    lv_obj_set_width(ui_LabelPreheat4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreheat4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreheat4, -123);
    lv_obj_set_y(ui_LabelPreheat4, -291);
    lv_obj_set_align(ui_LabelPreheat4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreheat4, "Temperature (°C)");
    lv_obj_set_style_text_align(ui_LabelPreheat4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPreheat4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_taSoakTemp = lv_textarea_create(ui_Panel21);
    lv_obj_set_width(ui_taSoakTemp, 420);
    lv_obj_set_height(ui_taSoakTemp, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_taSoakTemp, 0);
    lv_obj_set_y(ui_taSoakTemp, -13);
    lv_obj_set_align(ui_taSoakTemp, LV_ALIGN_CENTER);
    if("1234567890" == "") lv_textarea_set_accepted_chars(ui_taSoakTemp, NULL);
    else lv_textarea_set_accepted_chars(ui_taSoakTemp, "1234567890");
    lv_textarea_set_max_length(ui_taSoakTemp, 3);
    lv_textarea_set_placeholder_text(ui_taSoakTemp, "eg. 150");
    lv_textarea_set_one_line(ui_taSoakTemp, true);
    lv_obj_set_style_text_color(ui_taSoakTemp, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_taSoakTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_taSoakTemp, lv_color_hex(0xF7F2F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_taSoakTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_taSoakTemp, lv_color_hex(0x1879FF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_taSoakTemp, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Panel22 = lv_obj_create(ui_Panel33);
    lv_obj_set_width(ui_Panel22, 420);
    lv_obj_set_height(ui_Panel22, 80);
    lv_obj_set_align(ui_Panel22, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel22, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel22, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel22, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel22, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPreheat10 = lv_label_create(ui_Panel22);
    lv_obj_set_width(ui_LabelPreheat10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreheat10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreheat10, -123);
    lv_obj_set_y(ui_LabelPreheat10, -291);
    lv_obj_set_align(ui_LabelPreheat10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreheat10, "Duration (sec)");
    lv_obj_set_style_text_align(ui_LabelPreheat10, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPreheat10, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_taSoakDur = lv_textarea_create(ui_Panel22);
    lv_obj_set_width(ui_taSoakDur, 420);
    lv_obj_set_height(ui_taSoakDur, 40);
    lv_obj_set_x(ui_taSoakDur, 0);
    lv_obj_set_y(ui_taSoakDur, -13);
    lv_obj_set_align(ui_taSoakDur, LV_ALIGN_CENTER);
    if("1234567890" == "") lv_textarea_set_accepted_chars(ui_taSoakDur, NULL);
    else lv_textarea_set_accepted_chars(ui_taSoakDur, "1234567890");
    lv_textarea_set_max_length(ui_taSoakDur, 3);
    lv_textarea_set_placeholder_text(ui_taSoakDur, "eg. 120");
    lv_obj_set_style_text_color(ui_taSoakDur, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_taSoakDur, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_taSoakDur, lv_color_hex(0xF7F2F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_taSoakDur, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_taSoakDur, lv_color_hex(0x1879FF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_taSoakDur, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Panel34 = lv_obj_create(ui_Panel15);
    lv_obj_set_width(ui_Panel34, 440);
    lv_obj_set_height(ui_Panel34, 140);
    lv_obj_set_align(ui_Panel34, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel34, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel34, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel34, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel34, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel27 = lv_obj_create(ui_Panel34);
    lv_obj_set_width(ui_Panel27, 420);
    lv_obj_set_height(ui_Panel27, 40);
    lv_obj_set_align(ui_Panel27, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel27, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel27, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel27, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel27, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPreheat15 = lv_label_create(ui_Panel27);
    lv_obj_set_width(ui_LabelPreheat15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreheat15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreheat15, -123);
    lv_obj_set_y(ui_LabelPreheat15, -291);
    lv_obj_set_align(ui_LabelPreheat15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreheat15, "Phase 3: Ramp-Peak");
    lv_obj_set_style_text_font(ui_LabelPreheat15, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel20 = lv_obj_create(ui_Panel34);
    lv_obj_set_width(ui_Panel20, 420);
    lv_obj_set_height(ui_Panel20, 80);
    lv_obj_set_align(ui_Panel20, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel20, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel20, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel20, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel20, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPreheat11 = lv_label_create(ui_Panel20);
    lv_obj_set_width(ui_LabelPreheat11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreheat11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreheat11, -123);
    lv_obj_set_y(ui_LabelPreheat11, -291);
    lv_obj_set_align(ui_LabelPreheat11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreheat11, "Temperature rise (°C/s)");
    lv_obj_set_style_text_align(ui_LabelPreheat11, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPreheat11, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_taRampUpTempRise = lv_textarea_create(ui_Panel20);
    lv_obj_set_width(ui_taRampUpTempRise, 420);
    lv_obj_set_height(ui_taRampUpTempRise, 40);
    lv_obj_set_x(ui_taRampUpTempRise, 0);
    lv_obj_set_y(ui_taRampUpTempRise, -13);
    lv_obj_set_align(ui_taRampUpTempRise, LV_ALIGN_CENTER);
    if("1234567890" == "") lv_textarea_set_accepted_chars(ui_taRampUpTempRise, NULL);
    else lv_textarea_set_accepted_chars(ui_taRampUpTempRise, "1234567890");
    lv_textarea_set_max_length(ui_taRampUpTempRise, 3);
    lv_textarea_set_placeholder_text(ui_taRampUpTempRise, "eg. 4");
    lv_obj_set_style_text_color(ui_taRampUpTempRise, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_taRampUpTempRise, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_taRampUpTempRise, lv_color_hex(0xF7F2F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_taRampUpTempRise, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_taRampUpTempRise, lv_color_hex(0x1879FF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_taRampUpTempRise, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Panel35 = lv_obj_create(ui_Panel15);
    lv_obj_set_width(ui_Panel35, 420);
    lv_obj_set_height(ui_Panel35, 240);
    lv_obj_set_align(ui_Panel35, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel35, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel35, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel35, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel35, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel28 = lv_obj_create(ui_Panel35);
    lv_obj_set_width(ui_Panel28, 420);
    lv_obj_set_height(ui_Panel28, 40);
    lv_obj_set_align(ui_Panel28, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel28, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel28, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel28, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel28, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPreheat16 = lv_label_create(ui_Panel28);
    lv_obj_set_width(ui_LabelPreheat16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreheat16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreheat16, -123);
    lv_obj_set_y(ui_LabelPreheat16, -291);
    lv_obj_set_align(ui_LabelPreheat16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreheat16, "Phase 4: Reflow");
    lv_obj_set_style_text_font(ui_LabelPreheat16, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel23 = lv_obj_create(ui_Panel35);
    lv_obj_set_width(ui_Panel23, 420);
    lv_obj_set_height(ui_Panel23, 80);
    lv_obj_set_align(ui_Panel23, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel23, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel23, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel23, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel23, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPreheat12 = lv_label_create(ui_Panel23);
    lv_obj_set_width(ui_LabelPreheat12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreheat12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreheat12, -123);
    lv_obj_set_y(ui_LabelPreheat12, -291);
    lv_obj_set_align(ui_LabelPreheat12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreheat12, "Temperature (°C)");
    lv_obj_set_style_text_align(ui_LabelPreheat12, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPreheat12, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_taReflowTemp = lv_textarea_create(ui_Panel23);
    lv_obj_set_width(ui_taReflowTemp, 420);
    lv_obj_set_height(ui_taReflowTemp, 40);
    lv_obj_set_x(ui_taReflowTemp, 0);
    lv_obj_set_y(ui_taReflowTemp, -13);
    lv_obj_set_align(ui_taReflowTemp, LV_ALIGN_CENTER);
    if("1234567890" == "") lv_textarea_set_accepted_chars(ui_taReflowTemp, NULL);
    else lv_textarea_set_accepted_chars(ui_taReflowTemp, "1234567890");
    lv_textarea_set_max_length(ui_taReflowTemp, 3);
    lv_textarea_set_placeholder_text(ui_taReflowTemp, "eg. 150");
    lv_obj_set_style_text_color(ui_taReflowTemp, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_taReflowTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_taReflowTemp, lv_color_hex(0xF7F2F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_taReflowTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_taReflowTemp, lv_color_hex(0x1879FF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_taReflowTemp, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Panel24 = lv_obj_create(ui_Panel35);
    lv_obj_set_width(ui_Panel24, 420);
    lv_obj_set_height(ui_Panel24, 80);
    lv_obj_set_align(ui_Panel24, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel24, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel24, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel24, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel24, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPreheat13 = lv_label_create(ui_Panel24);
    lv_obj_set_width(ui_LabelPreheat13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreheat13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreheat13, -123);
    lv_obj_set_y(ui_LabelPreheat13, -291);
    lv_obj_set_align(ui_LabelPreheat13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreheat13, "Duration (sec)");
    lv_obj_set_style_text_align(ui_LabelPreheat13, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPreheat13, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_taReflowDur = lv_textarea_create(ui_Panel24);
    lv_obj_set_width(ui_taReflowDur, 420);
    lv_obj_set_height(ui_taReflowDur, 40);
    lv_obj_set_x(ui_taReflowDur, 0);
    lv_obj_set_y(ui_taReflowDur, -13);
    lv_obj_set_align(ui_taReflowDur, LV_ALIGN_CENTER);
    if("1234567890" == "") lv_textarea_set_accepted_chars(ui_taReflowDur, NULL);
    else lv_textarea_set_accepted_chars(ui_taReflowDur, "1234567890");
    lv_textarea_set_max_length(ui_taReflowDur, 3);
    lv_textarea_set_placeholder_text(ui_taReflowDur, "eg. 120");
    lv_obj_set_style_text_color(ui_taReflowDur, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_taReflowDur, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_taReflowDur, lv_color_hex(0xF7F2F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_taReflowDur, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_taReflowDur, lv_color_hex(0x1879FF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_taReflowDur, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Panel36 = lv_obj_create(ui_Panel15);
    lv_obj_set_width(ui_Panel36, 440);
    lv_obj_set_height(ui_Panel36, 240);
    lv_obj_set_align(ui_Panel36, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel36, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel36, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel36, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel36, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel36, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel29 = lv_obj_create(ui_Panel36);
    lv_obj_set_width(ui_Panel29, 420);
    lv_obj_set_height(ui_Panel29, 40);
    lv_obj_set_align(ui_Panel29, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel29, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel29, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel29, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel29, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPreheat17 = lv_label_create(ui_Panel29);
    lv_obj_set_width(ui_LabelPreheat17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreheat17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreheat17, -123);
    lv_obj_set_y(ui_LabelPreheat17, -291);
    lv_obj_set_align(ui_LabelPreheat17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreheat17, "Phase 5: Cooldown");
    lv_obj_set_style_text_font(ui_LabelPreheat17, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel30 = lv_obj_create(ui_Panel36);
    lv_obj_set_width(ui_Panel30, 420);
    lv_obj_set_height(ui_Panel30, 80);
    lv_obj_set_align(ui_Panel30, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel30, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel30, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel30, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel30, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPreheat18 = lv_label_create(ui_Panel30);
    lv_obj_set_width(ui_LabelPreheat18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreheat18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreheat18, -123);
    lv_obj_set_y(ui_LabelPreheat18, -291);
    lv_obj_set_align(ui_LabelPreheat18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreheat18, "Temperature (°C)");
    lv_obj_set_style_text_align(ui_LabelPreheat18, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPreheat18, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_taCooldownTemp = lv_textarea_create(ui_Panel30);
    lv_obj_set_width(ui_taCooldownTemp, 420);
    lv_obj_set_height(ui_taCooldownTemp, 40);
    lv_obj_set_x(ui_taCooldownTemp, 0);
    lv_obj_set_y(ui_taCooldownTemp, -13);
    lv_obj_set_align(ui_taCooldownTemp, LV_ALIGN_CENTER);
    if("1234567890" == "") lv_textarea_set_accepted_chars(ui_taCooldownTemp, NULL);
    else lv_textarea_set_accepted_chars(ui_taCooldownTemp, "1234567890");
    lv_textarea_set_max_length(ui_taCooldownTemp, 3);
    lv_textarea_set_placeholder_text(ui_taCooldownTemp, "eg. 150");
    lv_obj_set_style_text_color(ui_taCooldownTemp, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_taCooldownTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_taCooldownTemp, lv_color_hex(0xF7F2F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_taCooldownTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_taCooldownTemp, lv_color_hex(0x1879FF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_taCooldownTemp, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Panel31 = lv_obj_create(ui_Panel36);
    lv_obj_set_width(ui_Panel31, 450);
    lv_obj_set_height(ui_Panel31, 80);
    lv_obj_set_align(ui_Panel31, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel31, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel31, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel31, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel31, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPreheat19 = lv_label_create(ui_Panel31);
    lv_obj_set_width(ui_LabelPreheat19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreheat19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreheat19, -123);
    lv_obj_set_y(ui_LabelPreheat19, -291);
    lv_obj_set_align(ui_LabelPreheat19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreheat19, "Duration (sec)");
    lv_obj_set_style_text_align(ui_LabelPreheat19, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPreheat19, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_taCooldownDur = lv_textarea_create(ui_Panel31);
    lv_obj_set_width(ui_taCooldownDur, 420);
    lv_obj_set_height(ui_taCooldownDur, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_taCooldownDur, 0);
    lv_obj_set_y(ui_taCooldownDur, -13);
    lv_obj_set_align(ui_taCooldownDur, LV_ALIGN_CENTER);
    if("1234567890" == "") lv_textarea_set_accepted_chars(ui_taCooldownDur, NULL);
    else lv_textarea_set_accepted_chars(ui_taCooldownDur, "1234567890");
    lv_textarea_set_max_length(ui_taCooldownDur, 3);
    lv_textarea_set_placeholder_text(ui_taCooldownDur, "eg. 120");
    lv_obj_set_style_text_color(ui_taCooldownDur, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_taCooldownDur, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_taCooldownDur, lv_color_hex(0xF7F2F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_taCooldownDur, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_taCooldownDur, lv_color_hex(0x1879FF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_taCooldownDur, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Keyboard2 = lv_keyboard_create(ui_New_Profile);
    lv_obj_set_width(ui_Keyboard2, 460);
    lv_obj_set_height(ui_Keyboard2, 200);
    lv_obj_set_x(ui_Keyboard2, 0);
    lv_obj_set_y(ui_Keyboard2, 230);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Keyboard2, lv_color_hex(0x1879FF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard2, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Keyboard2, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BuCloseNewProfile, ui_event_BuCloseNewProfile, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_taProfileName, ui_event_taProfileName, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_taPreheatTempRise, ui_event_taPreheatTempRise, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_taSoakTemp, ui_event_taSoakTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_taSoakDur, ui_event_taSoakDur, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_taRampUpTempRise, ui_event_taRampUpTempRise, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_taReflowTemp, ui_event_taReflowTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_taReflowDur, ui_event_taReflowDur, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_taCooldownTemp, ui_event_taCooldownTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_taCooldownDur, ui_event_taCooldownDur, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard2, ui_taProfileName);
    lv_obj_add_event_cb(ui_Keyboard2, ui_event_Keyboard2, LV_EVENT_ALL, NULL);

}
