// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Reflow_Oven_screen_init(void)
{
    ui_Reflow_Oven = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Reflow_Oven, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Reflow_Oven, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Reflow_Oven, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Reflow_Oven, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Reflow_Oven, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Reflow_Oven, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Reflow_Oven, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Reflow_Oven);
    lv_obj_set_width(ui_Panel6, 450);
    lv_obj_set_height(ui_Panel6, 40);
    lv_obj_set_x(ui_Panel6, 32);
    lv_obj_set_y(ui_Panel6, -1);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x15171A), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_Panel6);
    lv_img_set_src(ui_Image4, &ui_img_fire_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 21
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_Image4, -210);
    lv_obj_set_y(ui_Image4, -200);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 280);

    ui_LaMenuTitle = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_LaMenuTitle, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_LaMenuTitle, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_LaMenuTitle, -116);
    lv_obj_set_y(ui_LaMenuTitle, -200);
    lv_obj_set_align(ui_LaMenuTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LaMenuTitle, "Soldering Phases");
    lv_obj_set_style_text_font(ui_LaMenuTitle, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart1 = lv_chart_create(ui_Reflow_Oven);
    lv_obj_set_width(ui_Chart1, 450);
    lv_obj_set_height(ui_Chart1, 190);
    lv_obj_set_x(ui_Chart1, 0);
    lv_obj_set_y(ui_Chart1, -316);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Chart1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart1, 200);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 250);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_Chart1, 0, 0);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 2, 5, 0, 1, false, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 2, 5, 0, 1, false, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    lv_obj_set_style_bg_color(ui_Chart1, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Chart1, lv_color_hex(0x15171A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Chart1, lv_color_hex(0xE6E2E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Chart1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Chart1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Chart1, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Chart1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Chart1, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Chart1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_Chart1, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_Chart1, lv_color_hex(0x101418), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Chart1, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Chart1, lv_color_hex(0x101418), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Chart1, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Chart1, lv_color_hex(0x101418), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Chart1, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_Chart1, lv_color_hex(0x4040FF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart1, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Chart1, lv_color_hex(0x101418), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Chart1, lv_color_hex(0x101418), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Chart1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Chart1, lv_color_hex(0x101418), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Chart1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LaActualTemperature = lv_label_create(ui_Chart1);
    lv_obj_set_width(ui_LaActualTemperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LaActualTemperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LaActualTemperature, -186);
    lv_obj_set_y(ui_LaActualTemperature, -64);
    lv_obj_set_align(ui_LaActualTemperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LaActualTemperature, "25°C");
    lv_obj_clear_flag(ui_LaActualTemperature,
                      LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Panel3 = lv_obj_create(ui_Reflow_Oven);
    lv_obj_set_width(ui_Panel3, 450);
    lv_obj_set_height(ui_Panel3, 65);
    lv_obj_set_x(ui_Panel3, 1);
    lv_obj_set_y(ui_Panel3, 48);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPreheat5 = lv_obj_create(ui_Panel3);
    lv_obj_set_width(ui_PanelPreheat5, 240);
    lv_obj_set_height(ui_PanelPreheat5, 60);
    lv_obj_set_x(ui_PanelPreheat5, -29);
    lv_obj_set_y(ui_PanelPreheat5, -108);
    lv_obj_set_align(ui_PanelPreheat5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelPreheat5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelPreheat5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelPreheat5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPreheat5, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPreheat5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPreheat5, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPreheat5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelPreheat5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelPreheat5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelPreheat5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelPreheat5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPreheat5 = lv_label_create(ui_PanelPreheat5);
    lv_obj_set_width(ui_LabelPreheat5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreheat5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreheat5, -140);
    lv_obj_set_y(ui_LabelPreheat5, -132);
    lv_obj_set_align(ui_LabelPreheat5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreheat5, "Phase 1: Preheat");
    lv_obj_set_style_text_align(ui_LabelPreheat5, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPreheat5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_laPreheatTempRise = lv_label_create(ui_PanelPreheat5);
    lv_obj_set_width(ui_laPreheatTempRise, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_laPreheatTempRise, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_laPreheatTempRise, -150);
    lv_obj_set_y(ui_laPreheatTempRise, -104);
    lv_obj_set_align(ui_laPreheatTempRise, LV_ALIGN_CENTER);
    lv_label_set_text(ui_laPreheatTempRise, "Temperatur:");
    lv_obj_set_style_text_align(ui_laPreheatTempRise, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_laPreheatTempRise, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Panel3);
    lv_obj_set_width(ui_Panel4, 186);
    lv_obj_set_height(ui_Panel4, 60);
    lv_obj_set_x(ui_Panel4, -112);
    lv_obj_set_y(ui_Panel4, 26);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x15171A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x15171A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel5, 186);
    lv_obj_set_height(ui_Panel5, 60);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel5, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x101418), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LaPreheatStatus = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_LaPreheatStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LaPreheatStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LaPreheatStatus, 156);
    lv_obj_set_y(ui_LaPreheatStatus, -207);
    lv_obj_set_align(ui_LaPreheatStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LaPreheatStatus, "Completed");

    ui_ImPreheatStatus = lv_img_create(ui_Panel5);
    lv_img_set_src(ui_ImPreheatStatus, &ui_img_check_png);
    lv_obj_set_width(ui_ImPreheatStatus, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_ImPreheatStatus, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_ImPreheatStatus, 106);
    lv_obj_set_y(ui_ImPreheatStatus, -8);
    lv_obj_set_align(ui_ImPreheatStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImPreheatStatus, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImPreheatStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImPreheatStatus, 250);

    ui_Panel1 = lv_obj_create(ui_Reflow_Oven);
    lv_obj_set_width(ui_Panel1, 450);
    lv_obj_set_height(ui_Panel1, 90);
    lv_obj_set_x(ui_Panel1, 1);
    lv_obj_set_y(ui_Panel1, 48);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPreheat6 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_PanelPreheat6, 240);
    lv_obj_set_height(ui_PanelPreheat6, 90);
    lv_obj_set_x(ui_PanelPreheat6, -29);
    lv_obj_set_y(ui_PanelPreheat6, -108);
    lv_obj_set_align(ui_PanelPreheat6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelPreheat6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelPreheat6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelPreheat6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPreheat6, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPreheat6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPreheat6, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPreheat6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelPreheat6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelPreheat6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelPreheat6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelPreheat6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPreheat6 = lv_label_create(ui_PanelPreheat6);
    lv_obj_set_width(ui_LabelPreheat6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreheat6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreheat6, -140);
    lv_obj_set_y(ui_LabelPreheat6, -132);
    lv_obj_set_align(ui_LabelPreheat6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreheat6, "Phase 2: Soak");
    lv_obj_set_style_text_align(ui_LabelPreheat6, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPreheat6, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_laSoakTemp = lv_label_create(ui_PanelPreheat6);
    lv_obj_set_width(ui_laSoakTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_laSoakTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_laSoakTemp, -150);
    lv_obj_set_y(ui_laSoakTemp, -104);
    lv_obj_set_align(ui_laSoakTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_laSoakTemp, "Temperatur:");
    lv_obj_set_style_text_align(ui_laSoakTemp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_laSoakTemp, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_laSoakDur = lv_label_create(ui_PanelPreheat6);
    lv_obj_set_width(ui_laSoakDur, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_laSoakDur, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_laSoakDur, -280);
    lv_obj_set_y(ui_laSoakDur, -34);
    lv_obj_set_align(ui_laSoakDur, LV_ALIGN_CENTER);
    lv_label_set_text(ui_laSoakDur, "Duration:");
    lv_obj_set_style_text_align(ui_laSoakDur, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_laSoakDur, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Panel2, 186);
    lv_obj_set_height(ui_Panel2, 90);
    lv_obj_set_x(ui_Panel2, -112);
    lv_obj_set_y(ui_Panel2, 26);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LaSoakStatus = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_LaSoakStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LaSoakStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LaSoakStatus, 156);
    lv_obj_set_y(ui_LaSoakStatus, -207);
    lv_obj_set_align(ui_LaSoakStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LaSoakStatus, "Completed");

    ui_ImSoakStatus = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_ImSoakStatus, &ui_img_check_png);
    lv_obj_set_width(ui_ImSoakStatus, LV_SIZE_CONTENT);   /// 33
    lv_obj_set_height(ui_ImSoakStatus, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_ImSoakStatus, 106);
    lv_obj_set_y(ui_ImSoakStatus, -8);
    lv_obj_set_align(ui_ImSoakStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImSoakStatus, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImSoakStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImSoakStatus, 250);

    ui_Panel7 = lv_obj_create(ui_Reflow_Oven);
    lv_obj_set_width(ui_Panel7, 450);
    lv_obj_set_height(ui_Panel7, 65);
    lv_obj_set_x(ui_Panel7, 1);
    lv_obj_set_y(ui_Panel7, 48);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPreheat7 = lv_obj_create(ui_Panel7);
    lv_obj_set_width(ui_PanelPreheat7, 240);
    lv_obj_set_height(ui_PanelPreheat7, 60);
    lv_obj_set_x(ui_PanelPreheat7, -29);
    lv_obj_set_y(ui_PanelPreheat7, -108);
    lv_obj_set_align(ui_PanelPreheat7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelPreheat7, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelPreheat7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelPreheat7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPreheat7, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPreheat7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPreheat7, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPreheat7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelPreheat7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelPreheat7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelPreheat7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelPreheat7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPreheat7 = lv_label_create(ui_PanelPreheat7);
    lv_obj_set_width(ui_LabelPreheat7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreheat7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreheat7, -140);
    lv_obj_set_y(ui_LabelPreheat7, -132);
    lv_obj_set_align(ui_LabelPreheat7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreheat7, "Phase 3: Ramp-Peak");
    lv_obj_set_style_text_align(ui_LabelPreheat7, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPreheat7, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_laRampPeakTempRise = lv_label_create(ui_PanelPreheat7);
    lv_obj_set_width(ui_laRampPeakTempRise, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_laRampPeakTempRise, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_laRampPeakTempRise, -150);
    lv_obj_set_y(ui_laRampPeakTempRise, -104);
    lv_obj_set_align(ui_laRampPeakTempRise, LV_ALIGN_CENTER);
    lv_label_set_text(ui_laRampPeakTempRise, "Rate:");
    lv_obj_set_style_text_align(ui_laRampPeakTempRise, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_laRampPeakTempRise, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Panel7);
    lv_obj_set_width(ui_Panel8, 186);
    lv_obj_set_height(ui_Panel8, 60);
    lv_obj_set_x(ui_Panel8, -112);
    lv_obj_set_y(ui_Panel8, 26);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel8, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LaRampPeakStatus = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_LaRampPeakStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LaRampPeakStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LaRampPeakStatus, 156);
    lv_obj_set_y(ui_LaRampPeakStatus, -207);
    lv_obj_set_align(ui_LaRampPeakStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LaRampPeakStatus, "Completed");

    ui_ImRampPeakStatus = lv_img_create(ui_Panel8);
    lv_img_set_src(ui_ImRampPeakStatus, &ui_img_check_png);
    lv_obj_set_width(ui_ImRampPeakStatus, LV_SIZE_CONTENT);   /// 33
    lv_obj_set_height(ui_ImRampPeakStatus, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_ImRampPeakStatus, 106);
    lv_obj_set_y(ui_ImRampPeakStatus, -8);
    lv_obj_set_align(ui_ImRampPeakStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImRampPeakStatus, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImRampPeakStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImRampPeakStatus, 250);

    ui_Panel9 = lv_obj_create(ui_Reflow_Oven);
    lv_obj_set_width(ui_Panel9, 450);
    lv_obj_set_height(ui_Panel9, 90);
    lv_obj_set_x(ui_Panel9, 1);
    lv_obj_set_y(ui_Panel9, 48);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel9, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel9, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPreheat8 = lv_obj_create(ui_Panel9);
    lv_obj_set_width(ui_PanelPreheat8, 240);
    lv_obj_set_height(ui_PanelPreheat8, 90);
    lv_obj_set_x(ui_PanelPreheat8, -29);
    lv_obj_set_y(ui_PanelPreheat8, -108);
    lv_obj_set_align(ui_PanelPreheat8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelPreheat8, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelPreheat8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelPreheat8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPreheat8, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPreheat8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPreheat8, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPreheat8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelPreheat8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelPreheat8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelPreheat8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelPreheat8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPreheat8 = lv_label_create(ui_PanelPreheat8);
    lv_obj_set_width(ui_LabelPreheat8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreheat8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreheat8, -140);
    lv_obj_set_y(ui_LabelPreheat8, -132);
    lv_obj_set_align(ui_LabelPreheat8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreheat8, "Phase 4: Reflow");
    lv_obj_set_style_text_align(ui_LabelPreheat8, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPreheat8, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_laReflowTemp = lv_label_create(ui_PanelPreheat8);
    lv_obj_set_width(ui_laReflowTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_laReflowTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_laReflowTemp, -150);
    lv_obj_set_y(ui_laReflowTemp, -104);
    lv_obj_set_align(ui_laReflowTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_laReflowTemp, "Temperatur:");
    lv_obj_set_style_text_align(ui_laReflowTemp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_laReflowTemp, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_laReflowDur = lv_label_create(ui_PanelPreheat8);
    lv_obj_set_width(ui_laReflowDur, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_laReflowDur, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_laReflowDur, -280);
    lv_obj_set_y(ui_laReflowDur, -34);
    lv_obj_set_align(ui_laReflowDur, LV_ALIGN_CENTER);
    lv_label_set_text(ui_laReflowDur, "Duration: ");
    lv_obj_set_style_text_align(ui_laReflowDur, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_laReflowDur, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_Panel9);
    lv_obj_set_width(ui_Panel10, 186);
    lv_obj_set_height(ui_Panel10, 90);
    lv_obj_set_x(ui_Panel10, -112);
    lv_obj_set_y(ui_Panel10, 26);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel10, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LaReflowStatus = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_LaReflowStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LaReflowStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LaReflowStatus, 156);
    lv_obj_set_y(ui_LaReflowStatus, -207);
    lv_obj_set_align(ui_LaReflowStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LaReflowStatus, "in Progress");

    ui_ImReflowStatus = lv_img_create(ui_Panel10);
    lv_img_set_src(ui_ImReflowStatus, &ui_img_running_png);
    lv_obj_set_width(ui_ImReflowStatus, LV_SIZE_CONTENT);   /// 33
    lv_obj_set_height(ui_ImReflowStatus, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_ImReflowStatus, 106);
    lv_obj_set_y(ui_ImReflowStatus, -8);
    lv_obj_set_align(ui_ImReflowStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImReflowStatus, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImReflowStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImReflowStatus, 220);

    ui_Panel11 = lv_obj_create(ui_Reflow_Oven);
    lv_obj_set_width(ui_Panel11, 450);
    lv_obj_set_height(ui_Panel11, 90);
    lv_obj_set_x(ui_Panel11, 1);
    lv_obj_set_y(ui_Panel11, 48);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel11, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel11, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel11, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPreheat9 = lv_obj_create(ui_Panel11);
    lv_obj_set_width(ui_PanelPreheat9, 240);
    lv_obj_set_height(ui_PanelPreheat9, 90);
    lv_obj_set_x(ui_PanelPreheat9, -29);
    lv_obj_set_y(ui_PanelPreheat9, -108);
    lv_obj_set_align(ui_PanelPreheat9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelPreheat9, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelPreheat9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelPreheat9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPreheat9, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPreheat9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPreheat9, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPreheat9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelPreheat9, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelPreheat9, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelPreheat9, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelPreheat9, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPreheat9 = lv_label_create(ui_PanelPreheat9);
    lv_obj_set_width(ui_LabelPreheat9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPreheat9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPreheat9, -140);
    lv_obj_set_y(ui_LabelPreheat9, -132);
    lv_obj_set_align(ui_LabelPreheat9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPreheat9, "Phase 5: Cooldown");
    lv_obj_set_style_text_align(ui_LabelPreheat9, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPreheat9, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_laCooldownTemp = lv_label_create(ui_PanelPreheat9);
    lv_obj_set_width(ui_laCooldownTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_laCooldownTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_laCooldownTemp, -150);
    lv_obj_set_y(ui_laCooldownTemp, -104);
    lv_obj_set_align(ui_laCooldownTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_laCooldownTemp, "Temperatur:");
    lv_obj_set_style_text_align(ui_laCooldownTemp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_laCooldownTemp, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_laCooldownDur = lv_label_create(ui_PanelPreheat9);
    lv_obj_set_width(ui_laCooldownDur, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_laCooldownDur, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_laCooldownDur, -280);
    lv_obj_set_y(ui_laCooldownDur, -34);
    lv_obj_set_align(ui_laCooldownDur, LV_ALIGN_CENTER);
    lv_label_set_text(ui_laCooldownDur, "Duration:");
    lv_obj_set_style_text_align(ui_laCooldownDur, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_laCooldownDur, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_Panel11);
    lv_obj_set_width(ui_Panel12, 186);
    lv_obj_set_height(ui_Panel12, 90);
    lv_obj_set_x(ui_Panel12, -112);
    lv_obj_set_y(ui_Panel12, 26);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel12, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel12, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel12, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LaCooldownStatus = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_LaCooldownStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LaCooldownStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LaCooldownStatus, 156);
    lv_obj_set_y(ui_LaCooldownStatus, -207);
    lv_obj_set_align(ui_LaCooldownStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LaCooldownStatus, "Pending");

    ui_ImCooldownStatus = lv_img_create(ui_Panel12);
    lv_img_set_src(ui_ImCooldownStatus, &ui_img_watch3_png);
    lv_obj_set_width(ui_ImCooldownStatus, LV_SIZE_CONTENT);   /// 33
    lv_obj_set_height(ui_ImCooldownStatus, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_ImCooldownStatus, 106);
    lv_obj_set_y(ui_ImCooldownStatus, -8);
    lv_obj_set_align(ui_ImCooldownStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImCooldownStatus, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImCooldownStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImCooldownStatus, 220);

    ui_Panel13 = lv_obj_create(ui_Reflow_Oven);
    lv_obj_set_width(ui_Panel13, 450);
    lv_obj_set_height(ui_Panel13, 65);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel13, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel13, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel13, lv_color_hex(0x15171A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BuStartReflow = lv_btn_create(ui_Panel13);
    lv_obj_set_width(ui_BuStartReflow, 160);
    lv_obj_set_height(ui_BuStartReflow, 60);
    lv_obj_set_x(ui_BuStartReflow, -117);
    lv_obj_set_y(ui_BuStartReflow, 360);
    lv_obj_set_align(ui_BuStartReflow, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BuStartReflow, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BuStartReflow, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_BuStartReflow, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BuStartReflow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BuStartReflow, lv_color_hex(0x1879FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BuStartReflow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BuStartReflowText = lv_label_create(ui_BuStartReflow);
    lv_obj_set_width(ui_BuStartReflowText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BuStartReflowText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BuStartReflowText, -122);
    lv_obj_set_y(ui_BuStartReflowText, 361);
    lv_obj_set_align(ui_BuStartReflowText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BuStartReflowText, "Start");

    ui_BuNewProfile = lv_btn_create(ui_Panel13);
    lv_obj_set_width(ui_BuNewProfile, 130);
    lv_obj_set_height(ui_BuNewProfile, 60);
    lv_obj_set_x(ui_BuNewProfile, 115);
    lv_obj_set_y(ui_BuNewProfile, 360);
    lv_obj_set_align(ui_BuNewProfile, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BuNewProfile, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BuNewProfile, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_BuNewProfile, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BuNewProfile, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BuNewProfile, lv_color_hex(0x1879FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BuNewProfile, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_BuNewProfile);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 119);
    lv_obj_set_y(ui_Label7, 362);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "New Profile");

    ui_BuLoadProfile = lv_btn_create(ui_Panel13);
    lv_obj_set_width(ui_BuLoadProfile, 130);
    lv_obj_set_height(ui_BuLoadProfile, 60);
    lv_obj_set_x(ui_BuLoadProfile, -117);
    lv_obj_set_y(ui_BuLoadProfile, 360);
    lv_obj_set_align(ui_BuLoadProfile, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BuLoadProfile, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BuLoadProfile, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_BuLoadProfile, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BuLoadProfile, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BuLoadProfile, lv_color_hex(0x1879FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BuLoadProfile, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_BuLoadProfile);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -122);
    lv_obj_set_y(ui_Label5, 361);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Load Profile");

    lv_obj_add_event_cb(ui_BuStartReflow, ui_event_BuStartReflow, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BuNewProfile, ui_event_BuNewProfile, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BuLoadProfile, ui_event_BuLoadProfile, LV_EVENT_ALL, NULL);
    uic_Panel1 = ui_PanelPreheat5;
    uic_Panel1 = ui_PanelPreheat6;
    uic_Panel1 = ui_PanelPreheat7;
    uic_Panel1 = ui_PanelPreheat8;
    uic_Panel1 = ui_PanelPreheat9;

}
